name: 'tag-push-action'
description: 'Retag and push multiplatform docker images'
author: 'Billgo <hi@billgo.me>'
inputs:
  src:
    required: true
    description: 'Source tag'
  dst:
    required: true
    description: 'Destination tags'
  docker-config-path:
    required: false
    description: 'Docker config file path'
runs:
  using: 'node16'
  main: 'lib/main.js'
