name: 'Tag-Push Action'
description: 'Retag and push multiplatform docker images'
author: 'Akhil Mohan'
inputs:
  src:
    required: true
    description: 'Source tag'
  dst:
    required: true
    description: 'Destination tags'
  docker-config-path:
    required: false
    description: 'Docker config file path'
runs:
  using: 'node16'
  main: 'dist/index.js'
